try:
    print(1/0)
except Exception as result:
    print(result)

# Exception 是所有程序异常类的父类